#ifndef CONFIG_H
#define CONFIG_H 

#define CHIP8_MEMORY_SIZE 4096
#define CHIP8_SCREEN_WIDTH 64
#define CHIP8_SCREEN_HEIGHT 32
#define CHIP8_SCREEN_TITLE "chip8 vm"
#define CHIP8_WINDOW_MULTIPLIER 10
#define CHIP8_WINDOW_MW ((CHIP8_WINDOW_MULTIPLIER) * (CHIP8_SCREEN_WIDTH))
#define CHIP8_WINDOW_MH ((CHIP8_WINDOW_MULTIPLIER) * (CHIP8_SCREEN_HEIGHT))

#endif
